In [3]:
import numpy as np
def soft(n):
    return np.exp(n)/np.sum(np.exp(n))

In [4]:
x = np.array([2,2.2,2.8,3,3.4,3.9,4,4.3])

In [5]:
output = soft(x)

In [6]:
output

array([0.02835306, 0.03463051, 0.0631009 , 0.07707161, 0.11497734,
       0.18956558, 0.20950237, 0.28279862])

In [7]:
import torch
y = torch.tensor(x)
y

tensor([2.0000, 2.2000, 2.8000, 3.0000, 3.4000, 3.9000, 4.0000, 4.3000],
       dtype=torch.float64)

In [8]:
out = torch.softmax(y, dim=0)
out

tensor([0.0284, 0.0346, 0.0631, 0.0771, 0.1150, 0.1896, 0.2095, 0.2828],
       dtype=torch.float64)

In [9]:
torch.sigmoid(y)

tensor([0.8808, 0.9002, 0.9427, 0.9526, 0.9677, 0.9802, 0.9820, 0.9866],
       dtype=torch.float64)

In [10]:
torch.relu(y)

tensor([2.0000, 2.2000, 2.8000, 3.0000, 3.4000, 3.9000, 4.0000, 4.3000],
       dtype=torch.float64)

In [11]:
torch.tanh(y)

tensor([0.9640, 0.9757, 0.9926, 0.9951, 0.9978, 0.9992, 0.9993, 0.9996],
       dtype=torch.float64)

In [12]:
#round(2.9) -> 3